apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygencs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oxygencs
  template:
    metadata:
      labels:
        app: oxygencs
    spec:
      containers:
        - name: oxygencs-container
          image: 191180611401/oxygencs-grp1-eq5:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "300m"
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: oxygencs-secrets
                  key: token
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: oxygencs-secrets
                  key: database-url
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: oxygencs-config-map
                  key: host
            - name: T_MIN
              valueFrom:
                configMapKeyRef:
                  name: oxygencs-config-map
                  key: t_min
            - name: T_MAX
              valueFrom:
                configMapKeyRef:
                  name: oxygencs-config-map
                  key: t_max
