name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install pipenv and other dependencies
        run: pip install pipenv pylint
      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run test
      - name: Run linter
        uses: wearerequired/lint-action@v2
        with:
          pylint: true
          pylint_args: "--disable=C0114,C0115,C0116,E0401,R0903,W0612,W0613,W0718"
