name: Docker Image Build-Publish CI

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_push_image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check out Repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs-grp1-eq5
      - name: Build and push Docker image (versionned)
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs-grp1-eq5:1.${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Build and push Docker image (latest)
        id: push_latest
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/oxygencs-grp1-eq5:latest
          labels: ${{ steps.meta.outputs.labels }}
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Create dot kube folder
        run: |
          mkdir -p $HOME/.kube
      - name: Setuping Kubernetes config
        run: |
         echo "${{ secrets.KUBECONF }}" > $HOME/.kube/config
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f infra/configMap.yaml
          kubectl apply -f infra/deployment.yaml
          kubectl apply -f infra/secret.yaml
      - name: Restart Kubernetes to get new image
        run: kubectl rollout restart deployment oxygencs-deployment
